INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('福州','402','fz','Fu Zhou ','FOC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('汉中','2705','hz','Han Zhong ','HZG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('塔城','3117','tc','Ta Cheng ','TCG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('迪庆','3320','dq','Di Qing ','DIG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('永州','1513','yz','Yong Zhou ','LLF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('德令哈市','42572','dlhs','De Ling Ha Shi','HXD','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('洛阳','1210','ly','Luo Yang','LYA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('且末县','42632','qmx','Qie Mo Xian ','IQM','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('昌都','3204','cd','Chang Du ','BPX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('敦煌市','505','dhs','Dun Huang Shi ','DNH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('保山','3304','bs','Bao Shan ','BSD','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阜阳','108','fy','Fu Yang ','FUG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('唐山','1013','ts','Tang Shan','TVS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('日喀则','3207','rkz','Ri Ka Ze ','RKZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黎平县','42121','lpx','Li Ping Xian ','HZH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('乌兰察布','2108','wlcb','Wu Lan Cha Bu','UCB','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('运城','2613','yc','Yun Cheng','YCU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('池州','109','cz','Chi Zhou ','JUH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('宁蒗彝族自治县','42191','nlyzzzx','Ning Lang Yi Zu Zi Zhi Xian ','NLH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('安庆','103','aq','An Qing ','AQG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('临沂','2411','ly','Lin Yi','LYI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('百色','703','bs','Bai Se ','AEB','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('长春','1802','cc','Chang Chun','CGQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('太原','2602','ty','Tai Yuan','TYN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('日照','2415','rz','Ri Zhao','RIZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('酒泉','508','jq','Jiu Quan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('稻城县','42031','dcx','Dao Cheng Xian ','DCY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('琼海市','905','qhs','Qiong Hai Shi','BAR','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('朝阳','1905','cy','Chao Yang','CHG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('宜春','1713','yc','Yi Chun','YIC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('乌鲁木齐','3102','wlmq','Wu Lu Mu Qi ','URC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('赣州','1704','gz','Gan Zhou','KOW','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('乌兰浩特市','40373','wlhts','Wu Lan Hao Te Shi','HLH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('白山','1804','bs','Bai Shan ','NBS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('铜仁','808','tr','Tong Ren ','TEN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿尔山市','40374','aess','A Er Shan Shi','YIE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('巴彦淖尔','2109','byne','Ba Yan Nao Er','RLK','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('海口','902','hk','Hai Kou ','HAK','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('满洲里市','40350','mzls','Man Zhou Li Shi','NZH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('三明','409','sm','San Ming ','SQJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('固原','2203','gy','Gu Yuan','GYU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('海拉尔区','40342','hleq','Hai La Er Qu','HLD','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('广元','2810','gy','Guang Yuan','GYS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('九寨沟县','2811','jzgx','Jiu Zhai Gou Xian ','JZH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('芒市','3324','ms','Mang Shi ','LUM','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('延吉市','40547','yjs','Yan Ji Shi ','YNJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('红原县','42014','hyx','Hong Yuan Xian ','AHJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('烟台','2419','yt','Yan Tai','YNT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('吐鲁番','3118','tlf','Tu Lu Fan ','TLQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('吉安','1705','ja','Ji An','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('深圳','619','sz','Shen Zhen','SZX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('林芝','3205','lz','Lin Zhi ','LZY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('邢台','1015','xt','Xing Tai ','XNT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('西昌市','2828','xcs','Xi Chang Shi ','XIC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('石家庄','1002','sjz','Shi Jia Zhuang ','SJW','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('宜宾','2825','yb','Yi Bin ','YBP','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('额济纳旗','40394','ejnq','E Ji Na Qi','EJN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('十堰','1410','sy','Shi Yan','WDS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('湛江','625','zj','Zhan Jiang ','ZHA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('无锡','1619','wx','Wu Xi','WUX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('嘉峪关','516','jyg','Jia Yu Guan','JGN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黔江区','315','qjq','Qian Jiang Qu ','JIQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿勒泰','3104','alt','A Le Tai ','AAT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('扬州','1622','yz','Yang Zhou','YTY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('梅州','614','mz','Mei Zhou ','MXZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('合肥','102','hf','He Fei','HFE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('齐齐哈尔','1111','qqhe','Qi Qi Ha Er ','NDG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('桂林','705','gl','Gui Lin ','KWL','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('梁平县','323','lpx','Liang Ping Xian','LIA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('石河子','3116','shz','Shi He Zi ','SHF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('荆州','1408','jz','Jing Zhou ','SHS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('怀化','1506','hh','Huai Hua ','HJJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('襄阳','1416','xy','Xiang Yang ','XFN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('庆阳','514','qy','Qing Yang ','IQN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('锡林浩特市','40380','xlhts','Xi Lin Hao Te Shi','XIL','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('广汉市','41911','ghs','Guang Han Shi ','GHN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('长治','2603','cz','Chang Zhi','CIH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('和田','3110','ht','He Tian ','HTN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿里','3203','al','A Li ','NGQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('张家界','1514','zjj','Zhang Jia Jie ','DYG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('泉州','408','qz','Quan Zhou ','JJN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('新源县','42678','xyx','Xin Yuan Xian ','NLT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('库尔勒市','42628','kels','Ku Er Le Shi ','KRL','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('台南','2904','tn','Tainan City','TNN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('东营','2406','dy','Dong Ying','DOY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('绵阳','2816','my','Mian Yang ','MIG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('佳木斯','1108','jms','Jia Mu Si ','JMU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('张家口','1016','zjk','Zhang Jia Kou ','ZQZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('鞍山','1903','as','An Shan','AOG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('台州','3424','tz','Tai Zhou ','HYN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('哈尔滨','1102','heb','Ha Er Bin ','HRB','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('天水','511','ts','Tian Shui ','THQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('河池','707','hc','He Chi ','HCJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('大连','1906','dl','Da Lian','DLC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('文山','3317','ws','Wen Shan ','WNH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('宜昌','1418','yc','Yi Chang ','YIH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('赤峰','2105','cf','Chi Feng','CIF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('安阳','1203','ay','An Yang ','AYN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('甘南','506','gn','Gan Nan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('金昌','507','jc','Jin Chang ','JIC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('中卫','2206','zw','Zhong Wei','ZHY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('景德镇','1706','jdz','Jing De Zhen','JDZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('康定市','42015','kds','Kang Ding Shi','KGT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('张掖','515','zy','Zhang Ye ','YZY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('营口','1915','yk','Ying Kou','YKH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('济宁','2408','jn','Ji Ning','JNG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('汕头','616','st','Shan Tou ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('三河市','40163','shs','San He Shi ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('青岛','2413','qd','Qing Dao','TAO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('广州','602','gz','Guang Zhou ','CAN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('长沙','1502','cs','Chang Sha ','CSX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('连云港','1610','lyg','Lian Yun Gang','LYG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('高雄','2906','gx','Kaohsiung City','KHH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('三亚','906','sy','San Ya ','SYX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('达州','2804','dz','Da Zhou ','DAX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('衡阳','1505','hy','Heng Yang ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('喀什','3111','ks','Ka Shi ','KHG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('玉树','2310','ys','Yu Shu','YUS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('万州区','302','wzq','Wan Zhou Qu ','WXN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('延安','2711','ya','Yan An ','ENY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('九江','1708','jj','Jiu Jiang','JIU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('伊春','1115','yc','Yi Chun ','LDS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('吉林','1808','jl','Ji Lin ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('马公','787136','mg','Magong City','MZG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('鸡西','1109','jx','Ji Xi ','JXA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('凯里市','42111','kls','Kai Li Shi ','KJH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('衢州','3419','qz','Qu Zhou ','JUZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('榆林','2712','yl','Yu Lin ','UYN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('普洱','3316','pe','Pu Er ','SYM','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('梧州','711','wz','Wu Zhou ','WUZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('惠州','609','hz','Hui Zhou ','HUZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿克苏','3103','aks','A Ke Su ','AKU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('常德','1503','cd','Chang De ','CGD','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('长海县','40414','chx','Chang Hai Xian','CNI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('富蕴县','42691','fyx','Fu Yun Xian ','FYN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('忻州','2610','xz','Xin Zhou','WUT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('临汾','2608','lf','Lin Fen','LFQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('东方市','911','dfs','Dong Fang Shi','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('呼和浩特','2102','hhht','Hu He Hao Te','HET','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('泸州','2814','lz','Lu Zhou','LZO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南昌','1702','nc','Nan Chang','KHN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('东莞','606','dg','Dong Guan','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黔西南','809','qxn','Qian Xi Nan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('蚌埠','104','bb','Beng Bu','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('天津','3000','tj','Tian Jin','TSN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('北海','704','bh','Bei Hai ','BHY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('锦州','1911','jz','Jin Zhou','JNZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('盐城','1621','yc','Yan Cheng','YNZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('淮安','1606','ha','Huai An','HIA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南通','1611','nt','Nan Tong','NTG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('大同','2604','dt','Da Tong','DAT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('安顺','803','as','An Shun ','AVA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('中山','627','zs','Zhong Shan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('义乌市','40810','yws','Yi Wu Shi ','YIW','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('韶关','618','sg','Shao Guan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿拉善左旗','40392','alszq','A La Shan Zuo Qi','AXF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('秦皇岛','1012','qhd','Qin Huang Dao ','BPE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南阳','1211','ny','Nan Yang ','NNY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('伊宁市','42672','yns','Yi Ning Shi ','YIN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('攀枝花','2820','pzh','Pan Zhi Hua ','PZI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('库车县','42639','kcx','Ku Che Xian ','KCA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('柳州','709','lz','Liu Zhou ','LZH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('龙岩','404','ly','Long Yan ','LCX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('舟山','3427','zs','Zhou Shan ','HSN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南京','1602','nj','Nan Jing','NKG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('大理','3306','dl','Da Li ','DLU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南宁','702','nn','Nan Ning ','NNG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('哈密','3109','hm','Ha Mi ','HMI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('遵义','811','zy','Zun Yi ','ZYI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('威海','2418','wh','Wei Hai','WEH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('布尔津县','42690','bejx','Bu Er Jin Xian ','KJI','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('恩施','1403','es','En Shi ','ENH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('贵阳','802','gy','Gui Yang ','KWE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('花莲市','785259','hls','Hualien City','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('策勒县','42668','clx','Ce Le Xian ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('广华街道','1960861','ghjd','Guang Hua Jie Dao','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('二连浩特市','40379','elhts','Er Lian Hao Te Shi','ERL','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('神农架','1412','snj','Shen Nong Jia ','HPG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('临沧','3311','lc','Lin Cang ','LNJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('温州','3426','wz','Wen Zhou','WNZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('上海','2500','sh','Shang Hai ','SHA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('吕梁','2607','ll','Lu Liang','LLV','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('乌海','2111','wh','Wu Hai','WUA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('通化','1811','th','Tong Hua ','TNH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('邯郸','1008','hd','Han Dan ','HDG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('大庆','1104','dq','Da Qing ','DQA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('兰州','502','lz','Lan Zhou ','LHW','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('成都','2802','cd','Cheng Du','CTU','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('兴城市','40494','xcs','Xing Cheng Shi','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('鄂尔多斯','2106','eeds','E Er Duo Si','DSN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('林西县','40320','lxx','Lin Xi Xian','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('拉萨','3202','ls','La Sa ','LXA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('常州','1604','cz','Chang Zhou','CZX','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('北京','200','bj','Bei Jing ','BJS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('厦门','414','sm','Xia Men ','XMN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('毕节','804','bj','Bi Jie ','BFJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黔南','805','qn','Qian Nan ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('抚远市','40645','fys','Fu Yuan Shi','FYJ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('武夷山市','413','wyss','Wu Yi Shan Shi ','WUS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('牡丹江','1110','mdj','Mu Dan Jiang ','MDG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('克拉玛依','3112','klmy','Ke La Ma Yi ','KRY','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('阿拉善右旗','40393','alsyq','A La Shan You Qi','RHT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('丽江','3312','lj','Li Jiang ','LJG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('重庆','300','cq','Chong Qing','CKG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('济南','2402','jn','Ji Nan','TNA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('安康','2703','ak','An Kang ','AKA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('龙川县','41723','lcx','Long Chuan Xian ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('苏州','1615','sz','Su Zhou','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('杭州','3402','hz','Hang Zhou ','HGH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('西宁','2302','xn','Xi Ning','XNN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('通辽','2110','tl','Tong Liao','TGO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黑河','1107','hh','Hei He ','HEK','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('包头','2104','bt','Bao Tou','BAV','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('井冈山市','1707','jgss','Jing Gang Shan Shi','JGS','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('银川','2202','yc','Yin Chuan','INC','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('望安','787140','wa','Wangan Township','WOT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('郑州','1202','zz','Zheng Zhou','CGO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('武汉','1402','wh','Wu Han ','WUH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('博尔塔拉','3106','betl','Bo Er Ta La ','BPL','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('宁波','3415','nb','Ning Bo ','NGB','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('漠河县','40679','mhx','Mo He Xian ','OHE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('六盘水','807','lps','Liu Pan Shui ','LPF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('格尔木市','42571','gems','Ge Er Mu Shi','GOQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('台中','2905','tz','Taichung City','RMQ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('台东','787149','td','Taitung City','TTT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('金门','2918','jm','Kinmen County','KNH','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('西安','2702','xa','Xi An ','SIA','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('南充','2818','nc','Nan Chong','NAO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('腾冲市','3323','tcs','Teng Chong Shi','TCZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('保定','1003','bd','Bao Ding ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('昭通','3321','zt','Zhao Tong ','ZAT','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('西双版纳','3318','xsbn','Xi Shuang Ban Na','JHG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('昆明','3302','km','Kun Ming ','KMG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('大兴安岭','1105','dxal','Da Xing An Ling ','','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('潍坊','2417','wf','Wei Fang','WEF','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('丹东','1907','dd','Dan Dong','DDG','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('沈阳','1902','sy','Shen Yang','SHE','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('徐州','1620','xz','Xu Zhou','XUZ','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('黄山','113','hs','Huang Shan ','TXN','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('佛山','607','fs','Fo Shan ','FUO','0');
INSERT INTO `city` (`cityName`, `cityCode`, `cityAbbr`, `cityEnglishName`, `cityIataCode`, `abroad`) VALUES('珠海','628','zh','Zhu Hai ','ZUH','0');